"""AI and decision model schemas for the REST API."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class AIAnalysisResponse(BaseModel):
    """Contextual narrative generated by Ollama LLM."""

    provider: str = Field(description="AI provider name, e.g. ollama")
    model: str = Field(description="LLM model name, e.g. llama3.2")
    explanation: str = Field(description="Contextual explanation of findings")
    evidence: list[str] = Field(default_factory=list, description="Extracted evidence points")
    contextual_findings: list[str] = Field(
        default_factory=list, description="Specific contextual findings"
    )
    requires_human_review: bool = Field(description="Whether manual expert review is advised")
    duration_seconds: float = Field(description="Inference time in seconds")
    tokens_used: int | None = Field(default=None, description="Reported token consumption if any")
    analyzed_at: datetime = Field(description="Timestamp of analysis generation")


class DecisionResultResponse(BaseModel):
    """Structured responses and probabilities from Ollama SystemOne."""

    provider: str = Field(description="Decision provider name, e.g. ollama_systemone")
    model: str = Field(description="Decision model identifier, e.g. tev1:4b")
    responses: dict[str, Any] = Field(
        default_factory=dict, description="Structured answers per question"
    )
    decision_probabilities: dict[str, Any] = Field(
        default_factory=dict,
        description="Probabilistic distributions over discrete choices evaluated by the model",
    )
    applicability_probability: float | None = Field(
        default=None,
        description="Model-assessed probability of applicability (0.0 to 1.0)",
    )
    urgency_score: float | None = Field(
        default=None,
        description="Prioritization score assigned by the model (0.0 to 1.0)",
    )
    latency_seconds: float = Field(description="Inference latency in seconds")
    timestamp: datetime = Field(description="Timestamp of decision evaluation")
