"""Initial schema

Revision ID: d4cfa3fb49a0
Revises:
Create Date: 2026-10-01 15:25:29.055054

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4cfa3fb49a0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_projects_name", "projects", ["name"], unique=False)
    op.create_index("ix_projects_path", "projects", ["path"], unique=True)
    op.create_table(
        "vulnerability_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_sync", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "project_components",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=True),
        sa.Column("version_type", sa.String(length=20), nullable=False),
        sa.Column("version_constraint", sa.String(length=255), nullable=True),
        sa.Column("source_file", sa.String(length=500), nullable=False),
        sa.Column("ecosystem", sa.String(length=50), nullable=False),
        sa.Column("component_type", sa.String(length=50), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_components_ecosystem", "project_components", ["ecosystem"], unique=False)
    op.create_index("ix_components_name", "project_components", ["name"], unique=False)
    op.create_index("ix_components_project", "project_components", ["project_id"], unique=False)
    op.create_table(
        "scans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("components_found", sa.Integer(), nullable=False),
        sa.Column("vulnerabilities_found", sa.Integer(), nullable=False),
        sa.Column("kev_matches", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_scans_project", "scans", ["project_id"], unique=False)
    op.create_index("ix_scans_started", "scans", ["started_at"], unique=False)
    op.create_index("ix_scans_status", "scans", ["status"], unique=False)
    op.create_table(
        "vulnerabilities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cve_id", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("vendor_project", sa.String(length=255), nullable=False),
        sa.Column("product", sa.String(length=255), nullable=False),
        sa.Column("vulnerability_name", sa.Text(), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=False),
        sa.Column("required_action", sa.Text(), nullable=False),
        sa.Column("date_added", sa.String(length=20), nullable=True),
        sa.Column("due_date", sa.String(length=20), nullable=True),
        sa.Column("known_ransomware_use", sa.String(length=50), nullable=False),
        sa.Column("cwes", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["vulnerability_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_vuln_cve_id", "vulnerabilities", ["cve_id"], unique=False)
    op.create_index("ix_vuln_cve_source", "vulnerabilities", ["cve_id", "source_id"], unique=True)
    op.create_index("ix_vuln_source", "vulnerabilities", ["source_id"], unique=False)
    op.create_index(
        "ix_vuln_vendor_product", "vulnerabilities", ["vendor_project", "product"], unique=False
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scan_id", sa.String(length=36), nullable=False),
        sa.Column("component_id", sa.String(length=36), nullable=False),
        sa.Column("vulnerability_id", sa.String(length=36), nullable=False),
        sa.Column("match_type", sa.String(length=30), nullable=False),
        sa.Column("match_confidence", sa.Float(), nullable=False),
        sa.Column("applicability", sa.String(length=30), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["component_id"], ["project_components.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vulnerability_id"], ["vulnerabilities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_matches_component", "matches", ["component_id"], unique=False)
    op.create_index("ix_matches_scan", "matches", ["scan_id"], unique=False)
    op.create_index("ix_matches_vulnerability", "matches", ["vulnerability_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_matches_vulnerability", table_name="matches")
    op.drop_index("ix_matches_scan", table_name="matches")
    op.drop_index("ix_matches_component", table_name="matches")
    op.drop_table("matches")
    op.drop_index("ix_vuln_vendor_product", table_name="vulnerabilities")
    op.drop_index("ix_vuln_source", table_name="vulnerabilities")
    op.drop_index("ix_vuln_cve_source", table_name="vulnerabilities")
    op.drop_index("ix_vuln_cve_id", table_name="vulnerabilities")
    op.drop_table("vulnerabilities")
    op.drop_index("ix_scans_status", table_name="scans")
    op.drop_index("ix_scans_started", table_name="scans")
    op.drop_index("ix_scans_project", table_name="scans")
    op.drop_table("scans")
    op.drop_index("ix_components_project", table_name="project_components")
    op.drop_index("ix_components_name", table_name="project_components")
    op.drop_index("ix_components_ecosystem", table_name="project_components")
    op.drop_table("project_components")
    op.drop_table("vulnerability_sources")
    op.drop_index("ix_projects_path", table_name="projects")
    op.drop_index("ix_projects_name", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
